name = "Tukan"
description = "Inspired from Toucan theme"
license = "AGPL"
homepage = "https://codeberg.org/salif/tukan"
# The minimum version of Zola required
min_version = "0.19.0"
# An optional live demo URL
demo = "https://salif.github.io/zola-themes-collection/demo/tukan/"
tags = ["Blog", "Multilingual"]

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
# Put all your custom variables here
title_pic = "$BASE_URL/favicon.ico"

# The theme author info: you!
[author]
name = "Salif Mehmed"
homepage = "https://salif.eu"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
author =  "Hugo Trentesaux"
homepage = "https://trentesaux.fr/"
repo = "https://git.42l.fr/HugoTrentesaux/toucan"
